analysis_chip : analysis.o main_analysis.o
	gcc -D GEOM=1 -o analysis_chip  -g analysis.o main_analysis.o

analysis.o : analysis.c
	gcc -D GEOM=1 -o  analysis.o -g -c analysis.c -W -Wall -ansi -pedantic

main_analysis.o : main_analysis.c
	gcc -D GEOM=1 -o  main_analysis.o -g -c main_analysis.c -W -Wall -ansi -pedantic
